### ISSUE TITLE
User data cleaner

### ISSUE THREAD

**Issue by Nicosoft** [catalyst/moodle-local_datacleaner#12]
I cannot run the user cleaner. It keeps running in 'dryrun' mode ... or am I doing something wrong?
I am using v2.3.5

Both say: 'Would ..."

Please see the screenshot.
-- screenshot 1: DryRun Mode
![dryrun_mode](https://cloud.githubusercontent.com/assets/4625910/19915849/3bfcd1f4-a109-11e6-8108-cb813b172024.png)

-- screenshot 2: Run Mode
![run_mode](https://cloud.githubusercontent.com/assets/4625910/19915852/40778e68-a109-11e6-8020-70c6c3bc0054.png)

**Comment by brendanheywood** [comment]
Hmm, In theory it should tell you why it failed if it does a dry run. Can you double check all these conditions are true and let me know which condition isn't being correctly reported back:

* It can only be run from the CLI. There is no GUI.
* We store the hostname in the cleaning configuration data. If the hostname matches production, DataCleaner will not run. If this data is missing then it will not run.
* Typically a refreshed database will be from a nightly snapshot and so the data should be slightly stale. If a non admin user has logged in recently, that's a sign this Moodle is being used, and the DataCleaner will not run.
* If cron has run recently, DataCleaner will not run. This should only be run on a data washing instance, cron should not be needed here.
* It can only be run if and only if a 'local_datacleaner_allowexecution = true;' has been added to config.php

**Comment by Nicosoft** [comment]
I double checked the conditions and I believe all the conditions are respected.

I an using Xdebug to follow the execution. In the screenshot 1, you can see the values used in function safety_checks() in --run mode. 
-- screenshot 1:
![1_run_values](https://cloud.githubusercontent.com/assets/4625910/19955904/3faeac4c-a1da-11e6-9b5c-46c4afc3892a.png)


When executed in --dryrun or --run the function safety_checks() returns FALSE. So I believe this is correct.

I have more concern when the object cleaner_users/clean is constructed. When executed in --run mode, cleaner_users\clean->dryrun = TRUE; **I believe the correct value should FALSE not TRUE.** (Please see the screenshot 2)
-- screenshot 2:
![2_run_construct](https://cloud.githubusercontent.com/assets/4625910/19955908/45a0318e-a1da-11e6-82e7-295e0d320711.png)

So obviously when the method execute() is called, because of the value of $dryrun, method stops before any update.
-- screenshot 3:
![3_run_execute](https://cloud.githubusercontent.com/assets/4625910/19955913/4e87e38c-a1da-11e6-8f32-767ea6e36033.png)

What do you think?

**Comment by roperto** [comment]
Hi Nico,

The data scrambler was refactored and a few issues with dryrun fixed, as a result I cannot reproduce that issue anymore.

Please, if you find out that there is a similar issue with the new version feel free to reopen it or create a new one, I will gladly look into it.

Cheers,

Daniel
