### ISSUE TITLE
Fix assertRegExp() is deprecated and will be removed in PHPUnit 10

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-local_datacleaner#136]
/var/www/html/lib/phpunit/classes/basic_testcase.php:64

7) cleaner_config_test::test_cleaner_config_getwhere
assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.

/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

8) cleaner_orphaned_sitedata\tests\unit\tempfiles_cleaner_test::test_it_removes_tempfiles
assertFileNotExists() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertFileDoesNotExist() instead.

**Comment by golenkovm** [comment]
This seems to be fixed for both Totara and Moodle
