### ISSUE TITLE
Scramble user data fails with database error

### ISSUE THREAD

**Issue by mikhailjan** [catalyst/moodle-local_datacleaner#14]
Hi,

While testing this plugin I get the following error:

== Running users cleaner ==
Scrambling the data of 6755 users.
 Scrambling user data    0% (0/168875)      !!! Error writing to database !!!
Potential coding error - existing temptables found when disposing database. Must be dropped!

When I turned on debug mode I saw it was trying to run the following query which seems to have an issue with the FROM clause:

UPDATE mdl_user u
SET firstname = mdl_temp_table.firstname,firstnamephonetic =mdl_temp_table.firstnamephonetic,alternatename = mdl_temp_table.alternatename
FROM mdl_temp_table
WHERE (1 + (u.id % 83)) = mdl_temp_table.id AND u.id IN (?,?,?...)

Plugin version: 2016051801
Moodle version: 2016052300.05 (3.1+)
MySQL version: 5.6.27

I would love to use this feature, let me now if you need any more info.

Thanks for the great plugin,
Mikhail

**Comment by brendanheywood** [comment]
Can you give a complete reproducible set of steps to get this? It looks to me like you started running it, it created the template table, then perhaps killed it and re-ran it? The temp tables should be deleted and the db driver checks that none are still around.

**Comment by mikhailjan** [comment]
This happened the first time I ran it. And there is no table called mdl_temp_table in the database afterwards. The same thing happens if I run it again.

Could it be that the SQL being generated is wrong?

```
Default exception handler: Error writing to database Debug: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM mdl_temp_table WHERE (1 + (u.id % 83)) = mdl_temp_table.id
            AND ' at line 1
```

**Comment by brendanheywood** [comment]
Possibly, it may actually be postgres specific sql which is barfing on mysql. If you are able to wrangle a patch together that would be great, or even if you can just amend it to work with mysql and I'll fold that in so it works side by side with postgres.

**Comment by mikhailjan** [comment]
I've changed the query and it seems to be working correctly. Here is the pull request https://github.com/catalyst/moodle-local_datacleaner/pull/15.

**Comment by roperto** [comment]
Hi Mikhail,

I just merged it into development branch and I should merge it to master soon.

Thank you for the patch,

Daniel

**Comment by roperto** [comment]
I am closing this issue we believe it has been solved. Feel free to reopen if something comes up.
