### ISSUE TITLE
Add 3.1 and 3.2 support

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_datacleaner#18]

**Comment by roperto** [comment]
I added to Travis build matrix MOODLE_31, MOODLE_32 and master.

I found no errors in the unit tests with both MySQL and Postgres.

My manual checks with the latest project I've been working with (Moodle 31) have not errored.

I added it as 3.1 / 3.2 compatible in release 2.3.7

Cheers,
