### ISSUE TITLE
url_replace is doing lots of redundant time expensive work

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_datacleaner#21]
* [x] do't ever replace on a column which isn't a text or varchar or similar
* [x] add extra debugging so that we can see the timings for each column + table, rather than just table granularity. We want to be able to see exactly which calls are expensive
* [x] change the 23 / 443 progress to the total number of columns being replaced not tables

**Comment by brendanheywood** [comment]
Can we close this @nhoobin ?

**Comment by nhoobin** [comment]
This can be closed.
