### ISSUE TITLE
Make a new cleaner for emails

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_datacleaner#27]
We usually turn off emails at the site or postfix level, but this will give us more options to do things differently

* [x] option to  set no email ever in db
* [x] option to set divertallemailsto
* [x] option to set divertallemailsexcept
* [x] option to add a fixed suffix to every email to render them (default to .invalid - see https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L5759-L5764)
* [x] option to ingore that suffix for limited list of users (regex?)

**Comment by nhoobin** [comment]
Implemented in PR #28.
