### ISSUE TITLE
Add possibility to disable a scheduled task with local_datacleaner

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-local_datacleaner#62]
Hi,

This feature request is targeted at the latest version of the plugin published on https://moodle.org/plugins/pluginversion.php?id=12918 and may be superseded by recent commits here in Github.

We would like to use local_datacleaner to disable a scheduled task in our washing box instances. The washing box instances have cron enabled by purpose and they have `$CFG->noemailever = true` set in config.php by purpose. This works generally fine. However, the auth_ldap\task\sync_task is configured to run every night in our production instance and would also run in the washing box instance.

There isn't a mechanism in Moodle core to disable or configure a scheduled task via config.php (like $CFG->foo for forcing core settings and $CFG->forced_settings for forcing plugin settings). That's why we would be grateful if local_datacleaner would offer the ability to disable and / or reconfigure a scheduled task when a washing box instance is cleaned.

I am aware that disabling and / or reconfiguring a scheduled task with local_datacleaner would not prevent an admin to re-enable / re-configure the scheduled task later. To force a scheduled task's configuration, an addition to Moodle core would be necessary.

Thanks,
Alex

**Comment by brendanheywood** [comment]
Yes this also seems useful and relatively straight forward.

Note that you could workaround it right now by using the matrix cleaner to change the settings in the ldap auth plugin so the task would still run but just do nothing.

I'm curious about the decision to have cron turned on for the washing instance, I can't see any valid reason for this. These washing boxes should be transient and 'headless' like they shouldn't need a webserver or cron. There is a small potential risk of cron running after the db is refreshed but before the cleaner runs if maintenance mode off. If it is on then cron won't run anyway. Depends on the harness you have which runs all this.

As a side note we have a large set of scripts which manage the db refreshes (part of our CI pipelines) and which calls the data cleaner. I have at various stages contemplated moving some parts of that layer into this plugin so it's managed consistently and isn't code that everyone need to write on their own.

**Comment by abias** [comment]
> Note that you could workaround it right now by using the matrix cleaner to change the settings in the ldap auth plugin so the task would still run but just do nothing.

This seems like a feasible workaround in general. However, the cleaner solution would still be to have the task disabled.

> I'm curious about the decision to have cron turned on for the washing instance, I can't see any valid reason for this. These washing boxes should be transient and 'headless' like they shouldn't need a webserver or cron. There is a small potential risk of cron running after the db is refreshed but before the cleaner runs if maintenance mode off. If it is on then cron won't run anyway. Depends on the harness you have which runs all this.

Some of our non-production instances are staging and testing environments which are used by end-users. That's why the instances should behave as good as possible like production. The non-production instances are also used to work with plugins which have some timed and require a runnig cron. As running cron on the non-production instances is not really expensive, we just had to disable outgoing mail and haven't encountered any problems with this approach since years.

> As a side note we have a large set of scripts which manage the db refreshes (part of our CI pipelines) and which calls the data cleaner. I have at various stages contemplated moving some parts of that layer into this plugin so it's managed consistently and isn't code that everyone need to write on their own.

Thanks for this side note. I will come back to you as soon as I need more help.

**Comment by brendanheywood** [comment]
> However, the cleaner solution would still be to have the task disabled.

haha - I see what you did there :)

> Some of our non-production instances are staging and testing environments which are used by end-users. That's why the instances should behave as good as possible like production.

Ah ok. I make a clear conceptual distinction between the box that the cleaner runs on (ie a washing machine) and the environment where the cleaned data gets refreshed to, ie test or stage. In simpler setups these can be the same box as long you think of the environment as being either in cleaner mode or in stage mode. So we are on the same page now, you just don't ever want cron running on the stage box while it is in 'cleaning mode', ie just after the db has been restored with prod data but before the cleaning process has completed. You don't really want any code running other than the cleaning code, which is why we run it in an isolated separate headless environment and then restore to the test / stage env.

**Comment by abias** [comment]
> I make a clear conceptual distinction between the box that the cleaner runs on (ie a washing machine) and the environment where the cleaned data gets refreshed to, ie test or stage. In simpler setups these can be the same box as long you think of the environment as being either in cleaner mode or in stage mode. So we are on the same page now, you just don't ever want cron running on the stage box while it is in 'cleaning mode', ie just after the db has been restored with prod data but before the cleaning process has completed. You don't really want any code running other than the cleaning code, which is why we run it in an isolated separate headless environment and then restore to the test / stage env.
Ah, ok. I have learned something new, too, and I understand now why you are calling the cleaning environments "washing boxes".
From this point of view, we have a combined solution which roughly goes like this:
* Disable cron in stage environment
* Clone wwwroot, moodledata and database from prod to stage enviromnent
* Clean the enviromnent with local_datacleaner
* Re-Enable cron in stage enviromnent
* Do whatever you like with stage enviromnent

**Comment by brendanheywood** [comment]
This one was done a while back:

https://github.com/catalyst/moodle-local_datacleaner/tree/master/cleaner/scheduled_tasks
