### ISSUE TITLE
orphaned_sitedata consumes large amounts of memory

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_datacleaner#8]
Possible a leak, or queries that should be resultsets

**Comment by brendanheywood** [comment]
get_sitedata_file() and get_database_files() are both static caches and need to be either be converted to work on sub trees (ie working with all aa, then ab, then ac hash prefixes)

OR another solution would be that both of those return iterators and do you an iterator based diff. This would probably mean we need indexing and sorting on the filehash in the moodle db which I don't think we do currently.

**Comment by roperto** [comment]
It was not really a leak, but it did grab the whole results at once.

Now its is done based on the first byte of the hash with much lower memory footprint.

**Comment by brendanheywood** [comment]
See ed88b66f0bb60e
