### ISSUE TITLE
Totara 12 - failing unit test on cleaner_config_test

### ISSUE THREAD

**Issue by azrek** [catalyst/moodle-local_datacleaner#80]
Getting following error when running unit tests on Totara 12:

1) cleaner_config_test::test_cleaner_config_getwhere
Property 'names' defined in 'cleaner_config_test' was not reset after the test!
Please either find a way to avoid using a class variable or make sure it get's unset in the tearDown method to avoid creating memory leaks.

/var/www/clients/totara/lib/phpunit/classes/advanced_testcase.php:521
/var/www/clients/totara/lib/phpunit/classes/advanced_testcase.php:105

To re-run:
 vendor/bin/phpunit cleaner_config_test local/datacleaner/cleaner/config/tests/config_test.php

**Comment by azrek** [comment]
Created pull request 81

https://github.com/catalyst/moodle-local_datacleaner/pull/81

**Comment by azrek** [comment]
1) cleaner_email_test::test_cleaner_email_suffix_append
Property 'config' defined in 'cleaner_email_test' was not reset after the test!
Please either find a way to avoid using a class variable or make sure it get's unset in the tearDown method to avoid creating memory leaks.

/var/www/clients/totara/lib/phpunit/classes/advanced_testcase.php:521
/var/www/clients/totara/lib/phpunit/classes/advanced_testcase.php:105

To re-run:
 vendor/bin/phpunit cleaner_email_test local/datacleaner/cleaner/email/tests/cleaner_email_test.php

**Comment by kristian-94** [comment]
This was fixed and merged, closing
