### ISSUE TITLE
Invasive test output

### ISSUE THREAD

**Issue by tomdickman** [catalyst/moodle-local_datacleaner#85]
When running unit tests, the plugin outputs a large amount of `Replacing URLs` information which is not particularly useful for a high level view of the unit tests for a Moodle instance.

Request a check is included and this output is turned off when unit tests are running to avoid cluttering and distorting the unit test output output.

Example:
![replacing_urls](https://user-images.githubusercontent.com/24489417/61255371-9f937c80-a7ab-11e9-9644-d0e9cc8008f6.png)

**Comment by kristian-94** [comment]
Hi @tomdickman , I have a PR for this issue: https://github.com/catalyst/moodle-local_datacleaner/pull/84

Do you want to review it?

**Comment by tomdickman** [comment]
No problems @kristian-94 I'll look at it now
