### ISSUE TITLE
The env matrix should use the admin settings api to save data instead of directly calling set_config

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_datacleaner#90]
ie if we mutate a saml setting we should not need to do stuff like this:

https://github.com/Peterburnett/SAMLrefresh/blob/master/SAML_refresh.php#L17-L20

So I think we need to:

1) test if the admin tree contains an admin setting with the same name as what we are cleaning
2) ~~if it exists the instantiate an admin setting object and calls it's methods to set and save the data. If there is exceptions then this is something we need to fix in the prod matrix data.~~ (see below, just call admin_write_settings($data);)  If this happens then we still need to either hard fail, or we should still set the data via set_config so there is no chance that prod data remains. But a hard failure is more correct because there might be prod data still saved in a secondary location which needs to be cleaned. Either way we need some noisy error logs
3) If there is no admin setting tree object then just call set_config as we are now

**Comment by brendanheywood** [comment]
This is broadly the same as what the gui is doing, this should be as simple as calling this:

https://github.com/moodle/moodle/blob/master/admin/search.php#L35

with some minor differences in error handling

**Comment by brendanheywood** [comment]
I think the easiest and safest is to blind call admin_write_settings($data); for each config item, and then if it barfs then call set_config

**Comment by brendanheywood** [comment]
On reflection there is a class of admin settings which in the gui might have multiple query params, eg 

admin_setting_configtime which renders 2 fields, and then parses those back.

So I think back to the original plan, instantiatie the object and call config_write($newvalue) on it

**Comment by Peterburnett** [comment]
Fixed in PR #91
